// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvnzxtnfukszaajkefot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bnp4dG5mdWtzemFhamtlZm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjUxNjEsImV4cCI6MjA2OTA0MTE2MX0.1uvSJ08iSqtOq7XJSd_g8p347pR23U5MqcUCklGZ0Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});